### ISSUE TITLE
The Merkle root construction is somewhat unsafe

### ISSUE THREAD

**Issue by bkomuves** [codex-storage/nim-poseidon2#5]
The Merkle root construction is somewhat unsafe, in the sense that calling the `merkleRoot` function with for example `[3,2,1]` gives the same result as calling with `[3,2,1,0]`.

So it can be only used for hashing fixed size arrays. 

Ideally we should change the construction so that there are no (practical) collisions between differently sized inputs. Some possible options:
- somehow include the length itself in the final root (for example adding a final `realRoot = hash(almostRoot,length)` step)
- pre-hash every element, and use 0 as _hashes_ as opposite to _values_ to pad (downside: makes it twice as slow)

If this is already solved in Codex, we should probably mirror that solution (but definitely synchronize the two)

Less ideally we should document this behaviour and/or enforce power-of-two-sized inputs.

**Comment by markspanbroek** [comment]
It's also unsafe for a small inputs (1 field element, or <31 bytes). Then it will just copy the input into the hash: https://github.com/codex-storage/nim-poseidon2/blob/40eac466e2e323eb6e8a11ebefbd37f91cd20e4f/poseidon2.nim#L81-L82

**Comment by bkomuves** [comment]
> It's also unsafe for a small inputs (1 field element, or <31 bytes). Then it will just copy the input into the hash:

Indeed, so there are two similar issues here:
- when Merkle hashing a sequence field elements, we have different sequences with the same hash
- when converting a sequence of bytes to a sequence of field elements, we have different bytestrings which results in the same sequence of field elements

Both can be solved by padding techniques:
- in the first case, for example we could add a final hash `H(length,preRoot)`
- in the second case, we can for example prepend (or append) the number of bytes as a field element.

Other similar solutions exist too. We have to fix some and document it, and in the case of Merkle tree, coordinate so that all Merkle trees do the same thing in the codebase.
